'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts.FPI

    Partial Public Class MyFPIAll

        '''<summary>
        '''ManagerDDL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManagerDDL As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UserLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SPGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SPGrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ExportBtn1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExportBtn1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CCHSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCHSql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''ManagerSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManagerSql As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
