'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts.FPI

    Partial Public Class NewFPIAll

        '''<summary>
        '''ManagerDDL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManagerDDL As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''FPIGv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPIGv As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ReviewBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReviewBtn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''errorlbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents errorlbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''EntitySql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EntitySql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''FPINewSQL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPINewSQL As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''LeadsSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LeadsSql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''ReviewedSQL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReviewedSQL As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''ManagerSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManagerSql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''UserLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserLbl As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
