'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts

    Partial Public Class NewYear

        '''<summary>
        '''FPIYearlbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPIYearlbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FPITb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPITb As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubmitBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubmitBtn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''FPISql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPISql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''PermittedSQL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PermittedSQL As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''Userlbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Userlbl As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
