'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts.FPI

    Partial Public Class Notify

        '''<summary>
        '''FPIGv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPIGv As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ExportBtn1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExportBtn1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UpdateBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateBtn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CCHSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CCHSql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''PermittedSQL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PermittedSQL As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''UserLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserLbl As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
