'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Layouts.FPI

    Partial Public Class Sent

        '''<summary>
        '''ManagerDDL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManagerDDL As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DateTB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DateTB As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DateTBExt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DateTBExt As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''FPIGv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPIGv As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ReviewBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReviewBtn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''errorlbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents errorlbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''EntitySql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EntitySql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''FPISQL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FPISQL As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''ManagerSql control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ManagerSql As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''UserLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserLbl As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
